#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "Antti Kivi"
email = "antti@anttikivi.com"

[signing]
behavior = "own"
backend = "gpg"
key = "B77AA9CD2C2BC68F3418F4AFC8BD979A718D8C84"
