#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "Antti Kivi"
email = "antti.kivi@visiosto.fi"

[signing]
behavior = "own"
backend = "gpg"
backends.gpg.program = "gpg"
key = "30BDAC10BFF22104983ABDCAC8392FAA9597BFD6"
