#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "Antti Kivi"
email = "antti@anttikivi.com"

[signing]
behavior = "own"
backend = "gpg"
backends.gpg.program = "gpg"
key = "A6274DA55A6868091EB573E8C0660739DD65FF31!"

[[--scope]]
--when.repositories = ["~/src/visiosto/"]

[--scope.user]
name = "Antti Kivi"
email = "antti.kivi@visiosto.fi"

[--scope.signing]
behavior = "own"
backend = "gpg"
backends.gpg.program = "gpg"
key = "44ABE720A7372780DEF85FCD5C6229C29B79528C!"
